<?php

declare(strict_types=1);

// Generated by Admin > Translations - edit through the UI when possible.
return array (
  'all_rights' => 'Hak cipta dilindungi.',
  'back_home' => 'Kembali ke Beranda',
  'cancel' => 'Batal',
  'error' => 'Terjadi kesalahan.',
  'loading' => 'Memuat...',
  'nav_blog' => 'Blog',
  'nav_contact' => 'Kontak',
  'nav_events' => 'Acara',
  'nav_home' => 'Beranda',
  'no_results' => 'Tidak ada hasil.',
  'page_not_found' => 'Halaman tidak ditemukan.',
  'read_more' => 'Selengkapnya',
  'rsvp' => 'Konfirmasi Kehadiran',
  'search' => 'Cari',
  'site_tagline' => 'Selamat datang di situs kami',
  'submit' => 'Kirim',
  'subscribe' => 'Berlangganan',
  'success' => 'Berhasil!',
  'unsubscribe' => 'Berhenti berlangganan',
);
